# Project information
site_name: mlfast
# defeine TOC or order of website-
nav:
  - Home: index.md

site_author: Abdul Jaweed
site_description: >-
  A Python ML Library 

# Repository
repo_name: Abdul-Jaweed/mlfast
repo_url: https://github.com/Abdul-Jaweed/mlfast

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Abdul-Jaweed
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/abdul-jaweed-datascientist/

extra_javascript:
  - javascripts/mathjax.js
  # - javascripts/tawk.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://www.linkedin.com/in/abdul-jaweed-datascientist/"  target="_blank" rel="noopener">Abdul Jaweed</a>