version: 2.1

jobs:
  build:
    docker:
      #- image: circleci/python:3.7.12
      - image: circleci/python:3.8.12
      - image: circleci/python:3.9.7

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo apt-get update && sudo apt-get install -y tox

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install flake8 pytest tox tox-gh-actions

      - run: tox
