version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    environment:
      MATRIX: |
        {"python-version": ["3.7", "3.8", "3.9"]}
    steps:
      - checkout
      - python/install:
          versions: <<MATRIX>>
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install flake8 pytest tox
            pip install -r requirements.txt
      - run:
          name: Test with tox
          command: tox
